import fs from 'node:fs'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import { uploadAndWait } from './support'

test('register, save a real analysis, play while authorized, and reopen its snapshot after deletion', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  const analysisId = await uploadAndWait(page)
  await page.getByRole('button', { name: '登录 / 注册' }).click()
  await page.getByRole('button', { name: '注册', exact: true }).click()
  await page.getByLabel('邮箱').fill('listener@example.test')
  await page.getByLabel('密码', { exact: true }).fill('private-password-123')
  await page.getByLabel('确认新密码').fill('private-password-123')
  await page.getByRole('button', { name: '创建账号' }).click()
  await expect(page.getByText('如果邮箱可用，验证链接已发送。完成验证后登录。')).toBeVisible()

  const metadata = JSON.parse(fs.readFileSync(path.resolve('tmp/e2e-runtime/current-run.json'), 'utf8')) as { runtime_root: string }
  const message = fs.readFileSync(path.join(metadata.runtime_root, 'last-mail.txt'), 'utf8')
  const token = message.match(/#verify=([A-Za-z0-9_-]+)/)?.[1]
  expect(token).toBeTruthy()
  await page.goto(`/#verify=${token}`)
  await expect(page.getByText('邮箱验证完成，现在可以登录。')).toBeVisible()

  await page.goto(`/?analysis=${analysisId}`)
  await page.getByRole('button', { name: '登录 / 注册' }).click()
  await page.getByLabel('邮箱').fill('listener@example.test')
  await page.getByLabel('密码', { exact: true }).fill('private-password-123')
  await page.getByRole('button', { name: '登录账号' }).click()
  await expect(page.getByText('已登录：listener@example.test')).toBeVisible()
  await page.getByRole('complementary', { name: '我的音乐空间' }).getByRole('button', { name: '收起' }).click()
  await expect(page.getByRole('button', { name: '保存这首分析' })).toBeVisible()
  await page.getByLabel('歌曲标题').fill('我的四和弦练习')
  await page.getByRole('button', { name: '保存这首分析' }).click()
  await expect(page.getByRole('button', { name: '已保存' })).toBeVisible()

  await page.getByRole('button', { name: '打开音乐空间侧边栏' }).click()
  await expect(page.getByText('私人保存 1 / 100 首。')).toBeVisible()
  await expect(page.getByText('我的四和弦练习')).toBeVisible()
  await expect(page.getByRole('button', { name: '修改标题' })).toHaveCount(0)
  await page.getByRole('button', { name: '我的四和弦练习的更多操作' }).click()
  await page.getByLabel('我的四和弦练习的偏好').selectOption('liked')
  await page.getByRole('navigation', { name: '音乐空间页面' }).getByRole('button', { name: '个人主页' }).click()
  await expect(page.getByText(/已喜欢 1 首/)).toBeVisible()
  await page.getByRole('navigation', { name: '音乐空间页面' }).getByRole('button', { name: '歌曲库' }).click()
  await page.getByRole('button', { name: '修改标题' }).click()
  await page.getByLabel('新歌曲标题').fill('我的四和弦练习（已保存）')
  await page.getByRole('button', { name: '保存标题' }).click()
  await expect(page.getByText('我的四和弦练习（已保存）')).toBeVisible()
  await page.getByLabel('搜索标题').fill('四和弦')
  await page.getByRole('button', { name: '搜索' }).click()
  await expect(page.getByText('我的四和弦练习（已保存）')).toBeVisible()
  await page.getByRole('button', { name: '我的四和弦练习（已保存）的更多操作' }).click()
  await page.screenshot({
    path: path.resolve('docs/evidence/user-memory/desktop-library-actions.png'),
    animations: 'disabled',
  })
  await page.getByRole('button', { name: '查看分析' }).click()
  await expect(page.getByRole('button', { name: '播放音频' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Music DNA' })).toBeVisible()
  await page.getByRole('navigation', { name: '分析功能' }).getByRole('button', { name: /结构地图/ }).click()
  await expect(page.getByRole('heading', { name: '结构地图' })).toBeVisible()
  fs.mkdirSync(path.resolve('docs/evidence/user-memory'), { recursive: true })
  await page.getByRole('button', { name: '打开音乐空间侧边栏' }).click()
  await page.getByRole('navigation', { name: '音乐空间页面' }).getByRole('button', { name: '个人主页' }).click()
  await expect(page.getByRole('heading', { name: '个人主页' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '数据与隐私' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '登录与会话' })).toBeVisible()
  await expect(page.getByText('此操作不可恢复')).toBeHidden()
  await page.getByText('注销账号', { exact: true }).click()
  await expect(page.getByText('此操作不可恢复')).toBeVisible()
  await page.screenshot({
    path: path.resolve('docs/evidence/user-memory/desktop-profile.png'),
    animations: 'disabled',
  })
  await page
    .getByRole('complementary', { name: '我的音乐空间' })
    .getByRole('button', { name: '收起' })
    .click()
  await page.screenshot({ path: path.resolve('docs/evidence/user-memory/desktop-saved-map.png'), fullPage: true })
  for (const width of [390, 800]) {
    await page.setViewportSize({ width, height: width === 390 ? 844 : 1000 })
    await expect(page.getByRole('heading', { name: '结构地图' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: path.resolve(`docs/evidence/user-memory/${width}-saved-map.png`), fullPage: true })
    const mobileNavigation = page.getByRole('navigation', { name: '主要页面' })
    await expect(mobileNavigation).toBeVisible()
    const navigationBox = await mobileNavigation.boundingBox()
    expect(navigationBox).not.toBeNull()
    expect(Math.abs((navigationBox?.y ?? 0) + (navigationBox?.height ?? 0) - (width === 390 ? 844 : 1000))).toBeLessThanOrEqual(2)
    await mobileNavigation.getByRole('button', { name: '个人' }).click()
    await expect(page.getByRole('heading', { name: '个人主页' })).toBeVisible()
    await expect(page.getByRole('heading', { name: '数据与隐私' })).toBeVisible()
    await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible()
    await page.waitForTimeout(350)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({
      path: path.resolve(`docs/evidence/user-memory/${width}-profile.png`),
      animations: 'disabled',
    })
    await mobileNavigation.getByRole('button', { name: '分析' }).click()
    await expect(page.getByRole('heading', { name: '结构地图' })).toBeVisible()
  }
  await page.getByRole('navigation', { name: '分析功能' }).getByRole('button', { name: /歌曲概览/ }).click()
  await page.getByText('管理分析数据', { exact: true }).click()
  await page.getByRole('checkbox', { name: '我了解删除不可恢复' }).check()
  await page.getByRole('button', { name: '永久删除分析', exact: true }).click()
  await expect(page.getByRole('heading', { name: '分析已永久删除' })).toBeVisible()
  await page
    .getByRole('navigation', { name: '主要页面' })
    .getByRole('button', { name: '歌曲库' })
    .click()
  await page.getByRole('button', { name: '查看分析' }).click()
  await expect(page.getByText(/正在复看私人歌曲库中的结构化分析/)).toBeVisible()
  expect(pageErrors).toEqual([])
})

test('account dialog recovers from forgotten and invalid passwords', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '登录 / 注册' }).click()
  const dialog = page.getByRole('dialog', { name: '欢迎回到音乐空间' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: '注册', exact: true }).click()
  await page.getByLabel('邮箱地址').fill('recovery@example.test')
  await page.getByLabel('密码', { exact: true }).fill('recovery-password-123')
  await page.getByLabel('确认新密码').fill('different-password-123')
  await expect(page.getByRole('button', { name: '创建账号' })).toBeDisabled()
  await page.getByLabel('确认新密码').fill('recovery-password-123')
  await page.getByRole('button', { name: '创建账号' }).click()
  await expect(page.getByRole('link', { name: '打开本地测试邮件链接' })).toBeVisible()
  await page.getByRole('link', { name: '打开本地测试邮件链接' }).click()
  await expect(page.getByText('邮箱验证完成，现在可以登录。')).toBeVisible()
  await page.getByLabel('邮箱地址').fill('recovery@example.test')
  await page.getByLabel('密码', { exact: true }).fill('wrong-password-123')
  await page.getByRole('button', { name: '登录账号' }).click()
  await expect(page.getByRole('alert').filter({ hasText: '邮箱、密码' })).toBeVisible()
  await page.getByRole('button', { name: '忘记密码？' }).click()
  await expect(page.getByRole('dialog', { name: '找回账号密码' })).toBeVisible()
  await page.getByRole('button', { name: '发送重置链接' }).click()
  await expect(page.getByRole('link', { name: '打开本地测试邮件链接' })).toBeVisible()
  await page.getByRole('link', { name: '打开本地测试邮件链接' }).click()
  await expect(page.getByRole('dialog', { name: '设置新密码' })).toBeVisible()
  await page.getByLabel('新密码', { exact: true }).fill('recovered-password-123')
  await page.getByLabel('确认新密码').fill('recovered-password-123')
  await page.getByRole('button', { name: '更新密码' }).click()
  await expect(page.getByText('密码已更新，请重新登录。')).toBeVisible()
  await page.getByLabel('邮箱地址').fill('recovery@example.test')
  await page.getByLabel('密码', { exact: true }).fill('recovered-password-123')
  await page.getByRole('button', { name: '登录账号' }).click()
  await expect(page.getByText('已登录：recovery@example.test')).toBeVisible()
})

test('account dialog stays usable on phone and tablet layouts', async ({ page }) => {
  for (const width of [390, 800]) {
    await page.setViewportSize({ width, height: width === 390 ? 844 : 1000 })
    await page.goto('/')
    const trigger = page
      .getByRole('navigation', { name: '主要页面' })
      .getByRole('button', { name: '个人' })
    await trigger.click()
    await expect(page.getByRole('dialog', { name: '欢迎回到音乐空间' })).toBeVisible()
    await page.waitForTimeout(400)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    fs.mkdirSync(path.resolve('docs/evidence/account-auth'), { recursive: true })
    await page.screenshot({ path: path.resolve(`docs/evidence/account-auth/${width}-login.png`) })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(trigger).toBeFocused()
  }
})
