from __future__ import annotations

import uuid
from datetime import datetime
from typing import Protocol

from museecho.domain.models import (
    AnalysisJobRecord,
    ChordEvent,
    EncryptedAudio,
    Evidence,
    Explanation,
    SectionEvent,
    TimeSeries,
    TrackAnalysis,
)


class AnalysisRepository(Protocol):
    def add(self, job: AnalysisJobRecord) -> None: ...
    def get(self, analysis_id: uuid.UUID) -> AnalysisJobRecord | None: ...
    def update(self, job: AnalysisJobRecord) -> None: ...
    def save_result(self, result: TrackAnalysis) -> None: ...
    def get_result(self, analysis_id: uuid.UUID) -> TrackAnalysis | None: ...
    def add_section(self, section: SectionEvent) -> None: ...
    def get_sections(self, analysis_id: uuid.UUID) -> list[SectionEvent]: ...
    def add_chord(self, chord: ChordEvent) -> None: ...
    def get_chords(self, analysis_id: uuid.UUID) -> list[ChordEvent]: ...
    def add_timeseries(self, ts: TimeSeries) -> None: ...
    def get_timeseries(self, analysis_id: uuid.UUID, kind: str) -> list[TimeSeries]: ...
    def add_evidence(self, evidence: Evidence) -> None: ...
    def get_evidence(self, analysis_id: uuid.UUID) -> list[Evidence]: ...
    def add_explanation(self, explanation: Explanation) -> None: ...
    def get_explanations(self, analysis_id: uuid.UUID) -> list[Explanation]: ...
    def delete_cascade(self, analysis_id: uuid.UUID) -> None: ...
    def get_expired_jobs(self, before: datetime) -> list[AnalysisJobRecord]: ...
    def get_non_terminal_jobs(self) -> list[AnalysisJobRecord]: ...


class AccessService(Protocol):
    def issue(self, analysis_id: uuid.UUID, expires_at: datetime) -> str: ...
    def authorize(self, analysis_id: uuid.UUID, raw_token: str) -> bool: ...


class EncryptedAudioStore(Protocol):
    def write(self, analysis_id: uuid.UUID, source: bytes, media_type: str) -> EncryptedAudio: ...
    def read_range(self, metadata: EncryptedAudio, start: int, end: int) -> bytes: ...
    def delete(self, metadata: EncryptedAudio) -> None: ...


class Analyzer(Protocol):
    def analyze(self, pcm: bytes) -> TrackAnalysis: ...


class ExplanationProvider(Protocol):
    def explain(self, question: str, evidence: tuple[Evidence, ...]) -> str: ...
