from __future__ import annotations

import uuid
from datetime import datetime
from typing import BinaryIO, Protocol

from museecho.domain.models import (
    AnalysisResult,
    ChordEvent,
    DecodedAudio,
    EncryptedAudioMetadata,
    Evidence,
    Explanation,
    ExplanationDraft,
    IssuedAccess,
    SectionEvent,
    TimeSeries,
    TrackAnalysis,
)
from museecho.domain.status import AnalysisJob


class AnalysisRepository(Protocol):
    def add(self, job: AnalysisJob) -> None: ...
    def get(self, analysis_id: uuid.UUID) -> AnalysisJob | None: ...
    def update(self, job: AnalysisJob) -> None: ...
    def list_active(self) -> list[AnalysisJob]: ...
    def save_result(self, result: AnalysisResult) -> None: ...
    def get_result(self, analysis_id: uuid.UUID) -> TrackAnalysis | None: ...
    def get_sections(self, analysis_id: uuid.UUID) -> list[SectionEvent]: ...
    def get_chords(self, analysis_id: uuid.UUID) -> list[ChordEvent]: ...
    def get_timeseries(self, analysis_id: uuid.UUID, kind: str) -> list[TimeSeries]: ...
    def get_evidence(self, analysis_id: uuid.UUID) -> list[Evidence]: ...
    def add_explanation(self, explanation: Explanation) -> None: ...
    def get_explanations(self, analysis_id: uuid.UUID) -> list[Explanation]: ...
    def delete_cascade(self, analysis_id: uuid.UUID) -> None: ...


class AccessService(Protocol):
    def issue(self, analysis_id: uuid.UUID, expires_at: datetime) -> IssuedAccess: ...
    def authorize(self, analysis_id: uuid.UUID, raw_token: str) -> bool: ...


class EncryptedAudioStore(Protocol):
    def write(
        self, analysis_id: uuid.UUID, source: BinaryIO, media_type: str
    ) -> EncryptedAudioMetadata: ...
    def read_range(self, metadata: EncryptedAudioMetadata, start: int, end: int) -> bytes: ...
    def delete(self, metadata: EncryptedAudioMetadata) -> None: ...


class Analyzer(Protocol):
    def analyze(self, pcm: DecodedAudio) -> AnalysisResult: ...


class ExplanationProvider(Protocol):
    def explain(self, question: str, evidence: tuple[Evidence, ...]) -> ExplanationDraft: ...
